啓発機能の追加
aizuHackathon/hackathon-back-app pull request #11
Opened 2022-05-08 10:36 UTC by RyuseiAndy

2022-05-10 04:02 UTC, daiki328 commented
基本、APIを作成するときはそのAPIがフロントでどう使われるかを考えた方がいいと思う（@hond あってる？）。
例えば今回の場合、Andyはhondの`GetAllUsers`を真似して書いたと思うけど、`GetAllUsers`って1人以上のユーザを取得してくるAPIなんだよね。啓発の場合は一つ以上の啓発をフロント側から取るわけではなく、何かしらの条件（idや時刻、体重や運動など）でマッチしたもの一つだけが欲しいと思うんだよね。
APIを実装するとき、このAPIがどう使われるかを考えて書けるようになるといいかも！
これを念頭にレビューするから、もしレビューでわからないことあったらコンタクトもらえると！

2022-05-10 04:10 UTC, daiki328 commented on go/router/router.go
> +	e.GET("/keihatus", r.keihatuHandler.Index)
`e.GET("/keihatu", r.keihatuHandler.Index)`の方がいいかな！

2022-05-10 04:10 UTC, daiki328 commented on go/handler/keihatu.go
> +
`"strconv"`を追加

2022-05-10 04:10 UTC, daiki328 commented on go/handler/keihatu.go
> +		Keihatus *response.Keihatus `json:"keihatus"`
Keihatu *response.Keihatu `json:"keihatu"`かな

2022-05-10 04:10 UTC, daiki328 commented on go/handler/keihatu.go
> +func (h *Keihatu) Index(c echo.Context) error {
```
func (h *Keihatu) Index(c echo.Context) error {
	id := c.QueryParam("id")
	if len(id) == 0 {
		return c.JSON(http.StatusBadRequest, "id is required")
	}
	ID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return c.JSON(http.StatusBadRequest, "id is invalid")
	}
	keihatu, err := h.keihatuService.GetKeihatuByID(ID)
	if err != nil {
		return c.JSON(http.StatusBadRequest, fmt.Sprintf("%v", err))
	}
	if keihatu == nil {
		return c.JSON(http.StatusBadRequest, "keihatu is not found")
	}

	return c.JSON(200, &JSONKeihatuIndex{
		Keihatu: response.NewKeihatu(keihatu),
	})
}
```
こうかな〜

2022-05-10 04:10 UTC, daiki328 commented on go/service/keihatu.go
> +		GetAllKeihatus() (*model.Keihatus, error)
`GetKeihatuByID(id int64) (*model.Keihatu, error)`かな

2022-05-10 04:10 UTC, daiki328 commented on go/service/keihatu.go
> +func (s *Keihatu) GetAllKeihatus() (*model.Keihatus, error) {
```
func (s *Keihatu) GetKeihatuByID(id int64) (*model.Keihatu, error) {
	m, err := s.repository.KeihatuByID(id)
```
かな

2022-05-10 04:10 UTC, daiki328 commented on go/repository/keihatu.go
> +		KeihatuByIDs(ids []int64) (*model.Keihatus, error)
`KeihatuByID(id int64) (*model.Keihatu, error)`かな

2022-05-10 04:10 UTC, daiki328 commented on go/repository/keihatu.go
> +	_, err := r.session.Select("*").From("Keihatus").Load(m)
```
func (r *Keihatu) KeihatuByID(id int64) (*model.Keihatu, error) {
	m := &model.Keihatu{}
	_, err := r.session.Select("*").From("Keihatus").Where("id = ?", id).Load(m)
```
かな

2022-05-10 04:10 UTC, daiki328 commented on go/model/keihatu.go
> +type Keihatus []Keihatu
これはいらないかな

2022-05-10 04:10 UTC, daiki328 commented on go/response/keihatu.go
> +	Keihatus []Keihatu
これはいらないかな

2022-05-10 04:10 UTC, daiki328 commented on go/response/keihatu.go
> +}
これはいらないかな

2022-05-10 04:27 UTC, hond0413 commented
> 基本、APIを作成するときはそのAPIがフロントでどう使われるかを考えた方がいいと思う（@hond あってる？）。 例えば今回の場合、Andyはhondの`GetAllUsers`を真似して書いたと思うけど、`GetAllUsers`って1人以上のユーザを取得してくるAPIなんだよね。啓発の場合は一つ以上の啓発をフロント側から取るわけではなく、何かしらの条件（idや時刻、体重や運動など）でマッチしたもの一つだけが欲しいと思うんだよね。とりあえず今回はID指定にした！ APIを実装するとき、このAPIがどう使われるかを考えて書けるようになるといいかも！ これを念頭にレビューするから、もしレビューでわからないことあったらコンタクトもらえると！

せやな、今は結構フロントと連絡取れてないからフロントがどう使いたいかわからんけど一応仕様書は作ってあるわけだからそれをベースに作っていくといいね
仕様書はフロントの方でも理解をもらってる部分ではあるから

2022-05-10 04:39 UTC, hond0413 commented on go/handler/keihatu.go
> +func (h *Keihatu) Index(c echo.Context) error {
```
if keihatu == nil { return c.JSON(http.StatusBadRequest, "keihatu is not found") }
```
keihatuのnilチェックはいらんかな、おそらく実装的に啓発は必ず何か返す仕様だからkeihatu == nilになる状態はerror != nilで担保できていないといけないと思う

2022-05-10 04:42 UTC, hond0413 commented
正直啓発系は結構仕様迷ってる部分もあっておそらくなんだけどフロント側から明示的にIDなんとかの啓発が欲しいってことはあまりないと思われるからバック側でランダムで啓発取得して返すって形でいいかなって思ってる。
 もし上を実装するとしたらrepositoryに存在するkeihatuのIDsを返すmethod追加、serviceで存在するIDsをもとにランダムでIDsを指定してkeihatu取得でもいいかなって思ってる。

2022-05-10 04:48 UTC, hond0413 commented
@RyuseiAndy 

> 仕様：啓発機能の追加しました。レビューお願いします。 疑問点：init.sql文のところでCREATEとINSERT文の揃え方どうしますか？ EX) CREATE TABLE Users (); CREATE TABLE Keihatus(); INSERT INTO Users(); INSERT INTO Keihatus();
> 
> or
> 
> CREATE TABLE Users (); INSERT INTO Users(); CREATE TABLE Keihatus(); INSERT INTO Keihatus();

CREATE TABLE Users (); CREATE TABLE Keihatus(); INSERT INTO Users(); INSERT INTO Keihatus();こっちにしてくれた方がいいかなdata何が入ってるかはみんな意識する必要ないかと思う重要なのはどう言った構成のtableが存在してるかだから

2022-05-20 13:12 UTC, hond0413 commented
とりあえずconflictしてるから最新のdevelop持ってきてconflict解消求む

2022-05-20 13:22 UTC, hond0413 requested changes

2022-05-22 14:44 UTC, merged