mongonAPI作成
aizuHackathon/hackathon-back-app pull request #12
Opened 2022-05-09 14:40 UTC by Shunsuke0425

- 以前のレビューからいくつか修正しました。
　①既存のコードを消してしまったので戻しました。
　②mongonについて単数の取得のため、関数の名前をGetMongonにした。

- 質問事項です。
　→今回のこのAPI作成においてmongonの取得って特定のidを指定してそのidにヒットするデータだけを返す、という感じですか？？

2022-05-10 04:59 UTC, hond0413 requested changes

2022-05-10 04:59 UTC, hond0413 commented on go/handler/mongon.go
> +}
なんかfile末尾の改行(EOF)がなくなりがちだから追加した方がいいと思う。
EOFはなんかfile操作した時とかのfileの最後の基準として設けられるものだから基本的には入れた方がいい

2022-05-10 04:59 UTC, hond0413 commented on go/repository/mongon.go
> +	_, err := r.session.Select("*").From("Mongons").Load(m)
なんか文言に関してはIDしていない時に全件返すのはまずいと思う。
空で良い気がする。

2022-05-10 04:59 UTC, hond0413 commented on go/service/mongon.go
> +func (s *Mongon) GetMongon() (*model.Mongons, error) {
repository層の仕様的に複数返すなら`GetMongon()`、単数なら`GetMongon()`かな
結構こういうところが混同してる。

2022-05-10 05:03 UTC, hond0413 commented
@Shunsuke0425 
> * 質問事項です。
>   　→今回のこのAPI作成においてmongonの取得って特定のidを指定してそのidにヒットするデータだけを返す、という感じですか？？
あくまでフロントはdbの中身の認知はないからIDで指定するというより以前ミーティングで話に上がってたけどログインしてなすぎる人には特定のmongon返すとかになると思うからそういうログイン状態だったり何かしらのバロメータに対してこちら側が計算して特定のIDの文言返すっていうのが適当だと思う。

ちなみに複数件数か単数件数かレスポンスのところは仕様にもまとまってるけど改めてフロントの人に聞いた方がいいと思うよ。
個人的には文言が複数必要な場面ってあまり浮かばないから単数でもいい気がするけど。

2022-05-15 15:17 UTC, Shunsuke0425 commented on go/handler/mongon.go
> +}
file一通り確認してfile操作用の改行追加しやした！

2022-05-15 15:19 UTC, Shunsuke0425 commented on go/repository/mongon.go
> +	_, err := r.session.Select("*").From("Mongons").Load(m)
今回は、ランダムにこっちでidを指定する感じになったのでrand関数を使用して書きましたrepositoryのmongon.goで書いた！

2022-05-15 15:19 UTC, Shunsuke0425 commented on go/service/mongon.go
> +func (s *Mongon) GetMongon() (*model.Mongons, error) {
これは関数の名前を変えるべきとか？

2022-05-20 13:24 UTC, hond0413 commented
最新のdevelopマージしてきてconflictの解消お願いします

2022-05-20 13:36 UTC, hond0413 requested changes
repositoryにロジック集約しちゃってるからrepositorはあくまでsqlを渡す感じでserviceにランダムな値を渡すとかそういうふうに編集お願いします🙇‍♂️

2022-05-20 13:36 UTC, hond0413 commented on go/model/mongon.go
> +	ID     int64
ちょくちょくインデントずれてるところあるから可能であればvscodeのデフォルトformatterをprettierとかにして修正してほしい

2022-05-20 13:36 UTC, hond0413 commented on go/repository/mongon.go
> +	_, err := r.session.Select("*").From("Mongons").Where("id = ?",rand.Intn(2) + 1).Load(m)
ランダムなmongonを返す機能はByIDsとは役割が別物だから作るなら別methodとして生成してほしい。
あとこの場合のランダムだと0~2かな？にしか対応してないから拡張性が低くなってるからdb内に存在するidを取得してきてそのidからランダムに選択されたidを用いてByIDsを叩くみたいな仕様にへこうしてほしい。
上記ロジックはservice等に含ませるといいと思うよ

2022-05-20 13:36 UTC, hond0413 commented on go/service/mongon.go
> +func (s *Mongon) GetMongon() (*model.Mongons, error) {
うん、単純に名前とやってることがあってないから

2022-05-22 13:23 UTC, Shunsuke0425 reviewed
randomにidを取得できるようにしました。正直コードぐちゃぐちゃで結果だけ。と言う感じです。アドバイスいただきたいです。

2022-05-22 13:42 UTC, merged