Feat/daiki328/get calorie
aizuHackathon/hackathon-back-app pull request #23
Opened 2022-05-18 03:25 UTC by daiki328

GET `http://localhost:8080/calorie?id=2&calorie_type=1`

2022-05-18 13:30 UTC, hond0413 requested changes
なんかこのprだけ名前やばい笑

2022-05-19 03:09 UTC, daiki328 commented on go/form/user.go
> +	UserName struct {
そうだね！これは大貴のやつ！

2022-05-19 04:18 UTC, daiki328 commented on go/handler/calorie.go
> +	if err != nil {
GETではとりあえず`model.CalorieType`にparseするのしかやってなくて、conflict面倒だから、POSTの方でvalidateかけた！POSTのマージ先をGETにするつもり！

2022-05-19 14:08 UTC, hond0413 approved these changes
LGTM

2022-05-19 21:19 UTC, merged