add: GET evolution
aizuHackathon/hackathon-back-app pull request #25
Opened 2022-05-18 06:45 UTC by daiki328

`http://localhost:8080/evolution?id=1`

2022-05-18 13:44 UTC, hond0413 requested changes
カロリー追加時に進化するかどうかって話は無くなった感じかな？

2022-05-18 13:44 UTC, hond0413 commented on go/handler/calorie.go
> +func (h *Calorie) GetStatus(c echo.Context) error {
`calorie.go`じゃなくて別fileでいいと思う

2022-05-18 13:44 UTC, hond0413 commented on go/handler/calorie.go
> +func (h *Calorie) GetStatus(c echo.Context) error {
`evolution.go`とかで

2022-05-18 13:44 UTC, hond0413 commented on go/service/calorie.go
> +	if float32(exerciseCalorie.Value)*0.7+float32(mealCalorie.Value)*0.3 > 11340 {
`float32(exerciseCalorie.Value)*0.7+float32(mealCalorie.Value)*0.3 > 11340`ここのロジック抜き出してローカル関数作成でいいと思うで

2022-05-18 13:44 UTC, hond0413 commented on go/service/calorie.go
> +	if float32(exerciseCalorie.Value)*0.7+float32(mealCalorie.Value)*0.3 > 11340 {
上にした方がifの条件が隠蔽されてコードとしてみやすい
ex 
```
func checkEvo(exeCal, mealCal) boolean {
ロジック
}
```

2022-05-18 13:44 UTC, hond0413 commented on go/repository/calorie.go
> +	for t.Next() {
dbrこんなめんどくさい書き方するんやな

2022-05-19 04:20 UTC, daiki328 commented
> カロリー追加時に進化するかどうかって話は無くなった感じかな？

そうね！`evolution`叩くことにした！

2022-05-19 04:57 UTC, daiki328 commented on go/repository/calorie.go
> +	for t.Next() {
他にもsolutionあるかもしれんけど、調べたところこれかなと

2022-05-19 14:09 UTC, hond0413 approved these changes
LGTM
直前に何機能も一気に実装マジで助かりました🙇‍♂️

2022-05-19 21:17 UTC, merged