MongonAPIのリファクタです
aizuHackathon/hackathon-back-app pull request #32
Opened 2022-05-24 08:14 UTC by Shunsuke0425

2022-05-24 12:22 UTC, hond0413 requested changes
とても良きだと思いまする！

2022-05-24 12:22 UTC, hond0413 commented on go/repository/mongon.go
> +	_, err := r.session.Select("*").From("Mongons").Where("id = ?", id).Load(m)
`From("mongons")`でいいと思う！

2022-05-24 12:22 UTC, hond0413 commented on go/repository/mongon.go
> +	_, err := r.session.Select("count(*) as value").From("Mongons").Load(idsLength)
同様に

2022-05-24 12:22 UTC, hond0413 commented on go/service/mongon.go
> +	Id, err := s.repository.RandomId()
ここの下にもerror処理を

2022-05-27 13:50 UTC, hond0413 approved these changes
一点だけレビュー漏れしてたところあるからそこの修正お願いします！

2022-05-27 13:50 UTC, hond0413 commented on go/repository/mongon.go
> +func (r *Mongon) MongonByRandom(id int64) (*model.Mongon, error) {
ここの名前`ById`でいいと思うランダムの時のみ使うわけではないから

2022-05-27 14:13 UTC, Shunsuke0425 reviewed
関数名修正しました🫡関連する所も直して動作確認済みです！

2022-05-27 14:24 UTC, hond0413 approved these changes
LGTM

2022-05-31 13:31 UTC, hond0413 commented
![LGTM](https://image.lgtmoon.dev/168211)

2022-05-31 13:40 UTC, merged