weight API作成
aizuHackathon/hackathon-back-app pull request #9
Opened 2022-04-30 05:30 UTC by daiki328

- userに紐づくweight作りました。

2022-04-30 06:24 UTC, hond0413 requested changes

2022-04-30 06:24 UTC, hond0413 commented on go/handler/weight.go
> +	id := c.QueryParam("id")
idはweightのidと混同するからここはuser_idの方が良さげ

2022-04-30 06:24 UTC, hond0413 commented on go/handler/weight.go
> +	intid, err := strconv.Atoi(id)
上の行がerrorハンドリングするわけでもないから一行で書いて良き。
```
userID, err := strconv.Atoi(c.QueryParam("user_id"))
```

2022-04-30 06:24 UTC, hond0413 commented on go/handler/weight.go
> +	intid, err := strconv.Atoi(id)
ついでにこれでint64にできる。
https://pkg.go.dev/strconv#ParseInt

2022-04-30 06:24 UTC, hond0413 commented on go/handler/weight.go
> +		return c.JSON(http.StatusBadRequest, "user is not found")
ここはあくまでweights is not found かなuserの処理はしてないから

2022-04-30 06:24 UTC, hond0413 commented on go/response/weight.go
> +		Weight_ID     int64   `json:"id"`
なんかちょくちょくインデントがやばいことになってるところがある。

2022-04-30 06:24 UTC, hond0413 commented on go/response/weight.go
> +		Weight_ID:  m.Weight_ID,
ここもインデントが。

2022-05-07 09:57 UTC, hond0413 commented on go/handler/weight.go
> +	user_id, err := strconv.ParseInt(c.QueryParam("id"), 10, 64)
なんかわいのmodelもそうだけど謎の_入りの変数が定義されてる...。

2022-05-07 09:57 UTC, hond0413 commented on go/model/user.go
> +	User_ID	int64
ここUser_IDにする意図はいかほどに？

2022-05-07 09:57 UTC, hond0413 commented on go/model/weight.go
> +	Weight_ID	int64
自分自身のIDはIDでForeignkeyのIDだけUserIDって形でいいと思う

2022-05-07 09:57 UTC, hond0413 commented on go/service/weight.go
> +func (s *Weight) GetAllWeights(id int64) (*model.Weights, error) {
全てのWeightではないからGetWeightsByUserIDとかが適当だと思われる。

2022-05-07 09:57 UTC, hond0413 commented on go/handler/weight.go
> +	if err != nil {
https://github.com/aizuHackathon/hackathon-back-app/pull/9#discussion_r862309559
と言ったもののそうするとidが与えられなかった場合のerrorと型変換できなかった場合のerrorの場合分けできてないから
```
ID := c.QueryParam("id")
if len(userID) == 0 {
// userIDがないよって処理
}
userId, err := strconv.ParseInt(ID, 10, 64)
if err != nil {
// intにできなかったよってerror
}
```
が正しそう
今のコードだと`localhost:8000/weight`を許容できてない。

2022-05-07 09:57 UTC, hond0413 commented on go/handler/weight.go
> +	if len(*weights) == 0 {
ここは後になるけどエラーになるかどうかはフロントと要相談やな
からの配列でもいいかもしれないから。

2022-05-08 06:00 UTC, hond0413 approved these changes
修正展終わったらLGTM

2022-05-08 06:00 UTC, hond0413 commented on postgres/init/init.sql
> +    User_ID SERIAL NOT NULL,
修正し直し忘れてる気がする。

2022-05-08 06:00 UTC, hond0413 commented on postgres/init/init.sql
> +    Weight_ID SERIAL NOT NULL,
こっちも同様に

2022-05-08 07:58 UTC, daiki328 commented
マージします

2022-05-08 07:58 UTC, merged